# Generated by Django 5.1.1 on 2024-10-06 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                ("movieId", models.AutoField(primary_key=True, serialize=False)),
                ("movieName", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Critics",
            fields=[
                ("criticId", models.AutoField(primary_key=True, serialize=False)),
                ("criticText", models.TextField(max_length=500)),
                ("criticRating", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movieName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Rating.movies"
                    ),
                ),
            ],
        ),
    ]
